record U0 type Exception
end

record U1 type Exception
end

program Exceptions

    function main()
        foo();
    end

    function foo()
        try
            bar();
        onException(ex U0)
            SysLib.writeStdout("Caught a U0 with message: '" :: ex.message :: "'");
        end
        bar();
    end

    function bar()
        baz();
    end

    firstBazCall boolean = true;
    function baz()
        if(firstBazCall)
            firstBazCall = false;
            throw new U0{message = "This is the U0 exception"};
        else
            throw new U1{message = "This is the U1 exception"};
        end
    end
end
