protect => {
   handle_error => {
        // do something else
   }
   fail(-1,'Oops')
}
