fcn f(b){
   try{
      onExitBlock("Exit code".println);
      if (b) throw(Exception.BadDay)
   }
   catch{ println(__exception," was thrown") }
   fallthrough{  println("No exception was thrown") }
   println("OK");
}
f(False); println("--------");
f(True);
